version: '2'
services:
  postgres:
    image: postgres:9.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: link_lab_development
  web:
    build: .
    command: apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs postgresql-client
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    volumes:
      - .:/linklab
    ports:
      - "3000:3000"
    links:
      - postgres